blurb_max: 50
date_format: '%d.%m.%Y'
home_page: index
markdown_exts:
- codehilite
- toc
- pykwiki.ext.tpl
- pykwiki.ext.post
postlist:
  max_pages: 5
  order_field: mtime
  order_type: descending
  per_page: 2
  post_type: preview
rss_max_entries: 20
site:
  author: "<a href='https://github.com/n0la'>@nola</a>, <a href='https://github.com/johannes-z'>@johannes-z</a>"
  base_url: "https://ehrpg.github.io/qstar-playtest"
  description: Placeholder Description
  keywords: placeholder
  title: "Q* Starter Module"
source_ext: .md
style: classic
theme: null
time_format: '%H:%M:%S'
timestamp_format: '%d.%m.%Y %H:%M'
upload_exts:
- .gif
- .jpg
- .jpeg
- .png
- .tiff
- .pdf
version: 2
web_prefix: "/qstar-playtest"
